### ISSUE TITLE
Cirela da Silva Lespier

### ISSUE THREAD

**Issue by cirelalespier** [BootCampAvanSanAnder/Slides#1]
https://github.com/cirelalespier/Roupas.git

**Comment by suspecie** [comment]
Cirela, quase que não vi o seu projeto, pq todo mundo abriou a issue neste repositorio aqui: https://github.com/BootCampAvanSanAnder/BootCampSantander

mas não tem problema!

Seu projeto está sensacional, inclusive verifiquei que já utilizou algumas coisas novas que aprendemos! parabéns!!
Depois caso você complete seu projeto com mais coisas que aprendemos, compartilhe novamente a url para podermos ver, combinado??

Parabéns pelo projeto!!!
